### ISSUE TITLE
Error in docs (my b)

### ISSUE THREAD

**Issue by ChapelR** [tmedwards/sugarcube-2#101]
From: http://www.motoslave.net/sugarcube/2/docs/#guide-state-sessions-and-saving-refreshing-and-restarting

> Whenever your story is first started or, for any reason, restarted—e.g., the browser window/tab was refreshed/reloaded—it undergoes its startup sequence. Several things occur each and every time startup happens, regardless of whether or not a playthrough session will be restored, an autosave loaded, **a regular save loaded**, or the starting passage run. First, the CSS, JavaScript, and Widget sections are processed. Next, the StoryInit special passage is processed. Finally, one of three things happen (in order): the existing playthrough session is restored, if it exists, else the autosave is loaded, if it exists and is configured to do so, else the starting passage is run.

Emphasis mine.

That at least heavily implies that the startup sequence happens when a "neutral" load occurs, meaning a saved game is loaded without the engine restarting. That's my error, so apologies.

**Comment by tmedwards** [comment]
Resolved by 39c64e9,
