### ISSUE TITLE
The :passagerender event is not fired for the StoryCaption passage

### ISSUE THREAD

**Issue by ezsh** [tmedwards/sugarcube-2#114]
The StoryCaption passage is a natural placeholder for various life information, it would be useful to be able to update its content.

**Comment by tmedwards** [comment]
No passage navigation event is fired for anything other than passage navigation.  That's not a bug, that's simply how those events work.

Beyond that, I'm unsure what that has to do with updating the contents of the `#story-caption` element—which is what I'm assuming you're actually referring to.

By default, the `#story-caption` element is automatically updated from the contents of the `StoryCaption` passage between the `:passagedisplay` and `:passageend` events (see: [Navigation Events](http://www.motoslave.net/sugarcube/2/docs/#events-navigation)).

If you've disabled the automatic update, then you can simply listen for one of the navigation events—e.g., `:passagedisplay`—and update the element from your handler.

**Comment by ezsh** [comment]
Thank you, I do something similar: there is an empty StoryCaption passage and the DOM content content is updated on `:passageend`. If I do that on `:passagedisplay`, SugarCube overwrites everything  with an empty passage. What is "disabled the automatic update", please?

**Comment by tmedwards** [comment]
[`Config.ui.updateStoryElements`](http://www.motoslave.net/sugarcube/2/docs/#config-api-property-ui-updatestoryelements).

**Comment by ezsh** [comment]
Thank you, with that set to `false` I can render to the side bar as needed. But sometimes setting that property to false makes the story menu and core `<nav>` element disappear too. I'd like it be gone too (actually, I want to render "-story" and "-core" buttons together in a single block), but can't understand the behaviour pattern. As far as `uiBarInit()` reads, the menu is created unconditionally and I can't find any code which removes the all the core buttons.

Do I miss something?

**Comment by tmedwards** [comment]
While some are conditional (see: `uiBarStart()`), there is nothing in the UI bar that removes all of the core menu elements, aside from destroying the entire bar.

With updates disabled, if the initial, and only, `StoryMenu` render yields no story menu items, then its element will be empty.  Other than that possibility, there is nothing in the UI bar that removes story menu elements, aside from destroying the entire bar.

**Comment by ezsh** [comment]
Thank you for clarifying this. May I suggest to add this bit to the `Config.ui.updateStoryElements` documentation?
