### ISSUE TITLE
Expand and Collapse Buttons

### ISSUE THREAD

**Issue by DelteRT** [tmedwards/sugarcube-2#116]
When editing a very long passage, it is difficult to navigate through so much text...

If there was a "Collapse and Expand" buttons to create groups, I think it would be easier.

![1](https://user-images.githubusercontent.com/81970381/113578200-70144b80-95f0-11eb-90d4-42a5ebcc1b60.PNG)
![2](https://user-images.githubusercontent.com/81970381/113578203-71457880-95f0-11eb-8e49-e5ed06cd5ac1.PNG)

**Comment by ChapelR** [comment]
This would be a Twine feature.
