### ISSUE TITLE
Make SugarCube CSS1Compat compliant in Firefox

### ISSUE THREAD

**Issue by Arkerthan** [tmedwards/sugarcube-2#120]
**Is your feature request related to a problem?**
Currently SugarCube games run in `BackCompat`/Quirks mode in Firefox (on Chromium they run in `CSS1Compat` mode). While this does not create problems itself many modern libraries expect to run in `CSS1mode` (For example [Popper.js](https://popper.js.org/), where [some placement options](https://popper.js.org/docs/v2/faq/) require `CSS1Compat` to work properly.)

SugarCube already has `<!DOCTYPE html>` specified, but something else seems to override it.

To see the mode the page is rendered in, type `document.compatMode` in the Browser Console.

**Describe the solution you'd like.**
SugarCube games run in `CSS1Compat` mode 

**Describe alternatives you've considered.**
Interestingly, removing the line `<meta charset="UTF-8" />` from the compiled HTML file makes Firefox run in `CSS1Compat` mode, though it generates an error about the missing encoding declaration, does support the thesis that something else breaks `CSS1Compat` mode though.

**Additional context.**
Firefox 88.0

**Comment by tmedwards** [comment]
By default SugarCube v2 runs in `CSS1Compat` mode in every browser I test it in.  From obsolete browsers like Opera 12 (Presto) to the latest mainstream browsers, including Firefox (as seen below).

![image](https://user-images.githubusercontent.com/101626/116961572-4d199d80-ac69-11eb-9043-5ea7838a64de.png)
![image](https://user-images.githubusercontent.com/101626/116961590-602c6d80-ac69-11eb-918b-741a0966dacd.png)

**Comment by Arkerthan** [comment]
Thanks for the confirmation.

Turns out it's probably a specific combination of plugins and something SugerCube/our game does that makes Firefox fall back to `BackCompat` mode.
