### ISSUE TITLE
all tracks in an AudioGroup play briefly on the first passagerender of the game

### ISSUE THREAD

**Issue by moates** [tmedwards/sugarcube-2#127]
**Describe the bug.**
This is a highly specific bug I just ran into. It may also be that I fundamentally don't understand what's behind the scenes for AudioRunner.

I wrote a simple (hacky) background track manager that controls background track transitions using Passage tags. In JS, on each :passagerender I check for any music tags, fade out all old tracks in the audio group :bgmusicgroup, and play the new track. 

On the first render of a game page with audio (in both Play and Debug modes), for a fraction of a second, all the tracks in the :bgmusicgroup play at once at a loud volume. 

**To Reproduce:**
[only-bans-sugarcube-audio-bug-report.txt](https://github.com/tmedwards/sugarcube-2/files/6987281/only-bans-sugarcube-audio-bug-report.txt)
I'm attaching a minimum reproducible bug story. (Just change the extension from .txt to .html) In StoryInit, you'll need to change the audio sources to whatever test tracks you have access to. 

**Expected behavior.**
The AudioRunner.[fadeOut docs ](http://www.motoslave.net/sugarcube/2/docs/#audiorunner-api-prototype-method-fadeout)say

> duration: (number) The number of seconds over which the tracks should be faded.
> fromVol: (optional, number) The starting volume level. If omitted, **defaults to the tracks' current volume level**

I would expect that the audio group's initial volume is set to zero, and thus when fading out silent tracks there should not be a sudden increase in volume for all tracks.  

**Project details.**

 - SugarCube Version: 2.34.1
 - Included Add-ons: none
 - Included Libraries: none
 - Compiler & Version: Twine 2.3.12

**Desktop details.**
 - OS & Version: windows
 - Browser & Version: reproduces on updated Chrome, Firefox, and Edge

Thank you! I love and appreciate Sugarcube. Shout out to you, maintainers!

**Comment by tmedwards** [comment]
> I would expect that the audio group's initial volume is set to zero…

Tracks default to 100% volume.  Groups are simply a way to collect tracks for ease of issuing actions (commands).

If you want certain tracks to start at any volume other than 100%, then you'll need to set them thus.

**Comment by moates** [comment]
I may be misunderstanding if there's a difference between the "current volume" and the "volume" property of a given track. 

At the beginning of the game, all tracks are manually stopped with AudioRunner.stop. Am I wrong to assume that the volume of a stopped track should be 0? And that the "current volume" of stopped tracks should also be 0?

**Comment by tmedwards** [comment]
The volume of a track is not affected by the stop action, which pauses the track and sets its time to zero.

If you want to set the volume at the same time, then you should also issue a volume action.

**Comment by moates** [comment]
Ah, okay. I was clearly misunderstanding. Thank you for your help and patience!
