### ISSUE TITLE
State.setVar() executes mid-parse when called from <<set>> or <<run>>

### ISSUE THREAD

**Issue by Sophismata** [tmedwards/sugarcube-2#129]
**Describe the bug.**
When a `<<run>>` or `<<set>>` macro is used with `State.setVar()` — e.g. to dynamically set a variable who's name is referred to by a second variable — **both** variables have their values changed.

**To Reproduce:**
Example passage text displaying this behaviour:
```html
<<set $foo to "$bar">>
<p>$$foo: "<<= $foo>>" (<<= typeof $foo>>)<br>
$$bar: <<= $bar>> (<<= typeof $bar>>)</p>
<<run State.setVar($foo, Math.PI)>>
<p>$$foo: "<<= $foo>>" (<<= typeof $foo>>)<br>
$$bar: <<= $bar>> (<<= typeof $bar>>)</p>
```

**Expected behaviour.**
Executing `<<run State.setVar($foo, Math.PI)>>` should change the value of variable `$bar` to Math.PI.
The value of variable `$foo` should not be changed.
```
$foo: "$bar" (string)
$bar: [undefined] (undefined)

$foo: "$bar" (string)
$bar: 3.141592653589793 (number)
```

**Actual behaviour.**
Both `$foo` and `$bar` are changed. Additionally, `$foo` is not set to `Math.PI`, but the stringified outcome of `Math.PI` (as this is happening while the macro is being parsed).
```
$foo: "$bar" (string)
$bar: [undefined] (undefined)

$foo: "3.141592653589793" (string)
$bar: 3.141592653589793 (number)
```

**Project details.**
 - SugarCube Version: 2.35.0
 - Compiler & Version: Tweego version 2.1.1+81d1d71 (2020-02-25T07:09:26Z) [windows/amd64]

**Desktop details.**
 - OS & Version: Windows 10
 - Browser & Version: Chrome 92.0.4515.159 (Official Build) (64-bit)

**Comment by Sophismata** [comment]
Thanks, that's good to hear. I'll check tonight & confirm — I'd thought the console reflected the results I'd seen but I could be mistaken.

**Comment by tmedwards** [comment]
@Sophismata Can this issue be closed?
