### ISSUE TITLE
CSS rule precedence requirements

### ISSUE THREAD

**Issue by zen14774** [tmedwards/sugarcube-2#132]
**Describe the bug.**

I encountered an issue when using Sugarcube and Tweego, when using multiple CSS files with `@import` rules, only the ones in the first file are actually applied.

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@import#description):
>Imported rules must precede all other types of rules, except `@charset` rules; as it is not a nested statement, `@import` cannot be used inside conditional group at-rules.

Both Tweego and SugarCube seem to apply some bundling of CSS, which break these rules. 

I opened a bug for Tweego [here](https://github.com/tmedwards/tweego/issues/34) explaining the issue in detail. Then I tried to work around the issue but found that SugarCube does something similar on top, which results in the same problem.

**Comment by zen14774** [comment]
I accidentally sent this early and I don't have time fill in all the details right now. I will re-open it when I can give more details.

**Comment by tmedwards** [comment]
For resources bundled into the compiled file, use a compiler that supports bundling libraries separately from the story resources—e.g., Tweego's module option (`-m SRC`, `--module=SRC`).

For resources included at runtime, look into the [`importScripts()`](http://www.motoslave.net/sugarcube/2/docs/#functions-function-importscripts) and [`importStyles()`](http://www.motoslave.net/sugarcube/2/docs/#functions-function-importstyles) functions.

**Comment by zen14774** [comment]
Thank you, bundling it separately with `-m` worked for the case of separate CSS files. I think it still breaks when using `[stylesheet]` but don't think I'm going to need that.
