### ISSUE TITLE
nobr breaks css

### ISSUE THREAD

**Issue by Muderru** [tmedwards/sugarcube-2#170]
**Describe the bug.**
I have gradient background `background: radial-gradient(ellipse at center, var(--color1) 0%,var(--color2) 40%,var(--color3) 100%);`. Without nobr macros everything looks fine. But if I use nobr in tags or passage body gradient is split up on repeating block areas.

**Expected behavior.**
I want my page graphically looks the same with and without nobr.

**Screenshots.**
Without nobr
![twine1](https://user-images.githubusercontent.com/7998756/177598168-f7aeb0e4-420e-4ad5-9f86-3e8d4f116373.png)
With nobr
![twine2](https://user-images.githubusercontent.com/7998756/177598190-c7911925-944b-4907-aa54-a6ca06475297.png)

**Project details.**
 - SugarCube Version: [2.36.1]
 - Compiler & Version: [Tweego 2.1.1]

**Desktop details.**
 - OS & Version: [Windows 10]
 - Browser & Version [Edge 103 (64-bit), Firefox 102 (64-bit)]

**Comment by tmedwards** [comment]
You're going to need to show more details than that.

1. What do the whole CSS rule(s) look like, don't just show some properties, and where are you setting those rule(s)?
2. What does the contents of that passage look like?

**Comment by hituro** [comment]
I think this is a css issue. I get the same effect if I don't supply a `background-size` property to the gradient. Probably an instance of the bug described here: https://stackoverflow.com/questions/43297619/why-doesnt-background-size-100-100-work-anymore-in-firefox

The following works in Firefox (assuming the style is applied to body)
```
background: radial-gradient(ellipse at center, red 0%,blue 40%,green 100%);
background-size: 100vw 100vh;
```

**Comment by Muderru** [comment]
Thanks, `background-size: 100vw 100vh;` is help. On Edge it works too.

> 1. What do the whole CSS rule(s) look like, don't just show some properties, and where are you setting those rule(s)?

I use slightly modified Bleached style where solid colors are replaced on gradients.


> 2\. What does the contents of that passage look like?

Invisible initialized loop.

**Comment by tmedwards** [comment]
Apparently this was a CSS issue.
