### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by janosbiroleite** [tmedwards/sugarcube-2#171]
Currently, I've been using Notepad++ to create syntax highlighting for Sugarcube. It's a lot of work to copy and paste each passage into Twine. Harlowe already has syntax highlighting integrated into Twine. When will we have this function for Sugarcube too?

**Comment by tmedwards** [comment]
Since my workstation is currently kaput, SugarCube v2's parser isn't really setup for such a thing, and I've got higher priority features to work on… I don't have any kind of estimate on when I might add syntax highlighting to v2.
