### ISSUE TITLE
StoryMenu can't access Config.debug

### ISSUE THREAD

**Issue by Airks** [tmedwards/sugarcube-2#19]
It seems that the passage StoryMenu can't access the Config API's variable `debug`.

When trying something like
`<<if Config.debug>>
/* some link */
<</if>>`
inside StoryMenu.tw, the menu in the UI bar never displays the aforementioned link.

Compiled with tweego.

**Comment by ChapelR** [comment]
The debug setting is ignored in `StoryMenu` for layout purposes.
