### ISSUE TITLE
JsDelivr CDN

### ISSUE THREAD

**Issue by ChapelR** [tmedwards/sugarcube-2#20]
Since you're on GitHub now, you could add the built Twine 2 format to the repo somewhere so users could add it to Twine 2 via the JSDelvr CDN: https://www.jsdelivr.com/

I serve my proofing format this way and I think it works pretty well, letting users grab specific versions (based on releases) or keep up to date by just getting the latest version. Not to mention you can better support the online version of the Twine 2 app.

**Comment by tmedwards** [comment]
Not a bad idea.

**Comment by tmedwards** [comment]
Done.  Resolved by ac6bebd.
