### ISSUE TITLE
Dialog.close() does not call the close callback

### ISSUE THREAD

**Issue by Kassy2048** [tmedwards/sugarcube-2#206]
**Describe the bug.**
If a close callback (`closeFn`) has been given when calling `Dialog.open()`, that callback is not invoked when closing the dialog from code using `Dialog.close()`. The callback is only called when the user manually closes the dialog using mouse or keyboard.

**To Reproduce:**
```js
  Dialog.setup("Test");
  Dialog.wiki('<<link "Click Me">><<set Dialog.close()>><</link>>');
  Dialog.open({}, () => {
    alert("Close callback called!");
  });
```

**Expected behavior.**
Clicking the "Click Me" link should close the dialog and show the alert message. It only closes the dialog though, so the close callback is not called. Clicking on the "X" close button instead *does* invoke the callback.

**Workaround.**
```js
  Dialog.setup("Test");
  Dialog.wiki('<<link "Click Me">><<set jQuery("#ui-dialog-close").trigger("click")>><</link>>');
  Dialog.open({}, () => {
    alert("Close callback called!");
  });
```

**Project details.**
 - SugarCube Version: 2.36.1

**Comment by tmedwards** [comment]
It was the intended behavior, so not a bug.

Regardless.  The behavior was changed, back in November 2022, via commit 96ddf9a to align with your feature request.

**Comment by Kassy2048** [comment]
Aw  sorry, I couldn't find a ticket or discussion about that behavior. Thanks for having changed it then 😁
