### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by zen14774** [tmedwards/sugarcube-2#211]
I noticed a few links that point to articles in the Twine wiki that are gone and now redirect to the Twine cookbook front page. There's at least one in the [images](https://www.motoslave.net/sugarcube/2/docs/#markup-image) section and two in the [expressions](https://www.motoslave.net/sugarcube/2/docs/#twinescript-expressions) section.

**Comment by MalifaciousGames** [comment]
There is also one in the [`<<actions>>` macro description](https://www.motoslave.net/sugarcube/2/docs/#macros-macro-actions) .

**Comment by tmedwards** [comment]
I'm fairly sure these have all been rectified in the current development documentation, so I'm marking this as done.

I'll close out the issue when I publish the next release.
