### ISSUE TITLE
Enhance <<unset>> to handle object properties

### ISSUE THREAD

**Issue by tmedwards** [tmedwards/sugarcube-2#223]
What it says on the tin.

Users attempting to use `<<unset>>` to delete properties from objects stored in story and temporary variables is a common issue.  The two obvious solutions are:

1. Add a warning to its documentation entry, that no one will bother to read.
2. Enhance it to be able to handle deleting properties from objects.

Option 2 is the clear choice here.

### `<<unset variableList>>`

Unsets story $variables, temporary \_variables, and properties of objects stored within either.

#### History:

* `v2.0.0`: Introduced.
* `v2.37.0`: Added ability to unset object properties.

#### Arguments:

* **`variableList`:** A list of story variables, temporary variables, or properties of objects stored within either.

#### Examples:

Basic usage, unsetting story and temporary variables.

```
<<unset $rumors>>
<<unset _npc>>

<<unset $rumors, _npc, _choices, $job>>
```

Unsetting object properties.

```
<<unset _choices.b>>
<<unset $towns['port ulster'].rumors>>

<<unset _choices.b, $towns['port ulster'].rumors, $pc.notes, _park.rides['wheel of death']>>
```

**Comment by greyelf** [comment]
@tmedwards 
And if the end-user did `<<unset $towns>>` when `$towns` contained an Object with properties that would cause the `$towns` variable itself to be unset?

**Comment by tmedwards** [comment]
It will do exactly what it does now, completely remove the story variable.

The only difference the change to `<<unset>>` will make is when doing something like `<<unset $towns.adelaide>>`.

* **In versions ≤2.36.1:** That will remove the story variable `$towns`.
* **In versions ≥2.37.0:** That will remove the property `adelaide` from the object contained within the story variable `$towns`.
