### ISSUE TITLE
<<cycle>> + cleanupWikifierOutput() encloses content in a <p>

### ISSUE THREAD

**Issue by hituro** [tmedwards/sugarcube-2#231]
**Describe the bug.**
When `Config.cleanupWikifierOutput = true`, the contents of a `<<cycle>>` macro are wrapped in a `<p>` tag after the first click. 

**To Reproduce:**
The following code, in a file with `Config.cleanupWikifierOutput = true`
```hmtl
<<nobr>><<cycle "_blah">>
	<<option "Towel">>
	<<option "π" 3.14159>>
	<<option 42>>
	<<option 69>>
	<<option "∞" Infinity>>
<</cycle>><</nobr>>
```
Shows the issue

**Expected behavior.**
There shouldn't be a `<p>` tag, since `Config.cleanupWikifierOutput = true` isn't supposed to apply to sub-wikis

**Screenshots.**
Generated HTML on page load
```html
<p><a id="cycle--blah" class="macro-cycle" role="button" tabindex="0">Towel</a></p>
```
HTML after first click
```html
<a id="cycle--blah" class="macro-cycle" role="button" tabindex="0"><p>π</p></a>
```

**Project details.**
 - SugarCube Version: 2.36.1

**Comment by tmedwards** [comment]
Duplicate #154.
