### ISSUE TITLE
Document Math.easeInOut?

### ISSUE THREAD

**Issue by BawdyInkSlinger** [tmedwards/sugarcube-2#267]
Sugarcube source code defines [`Math.easeInOut`](https://github.com/tmedwards/sugarcube-2/blob/27903a854b7bedbb9fa60efa33e47c99bab7a359/src/lib/extensions.js#L1299) but it's undocumented. Is this intentional?

**Comment by greyelf** [comment]
@BawdyInkSlinger 
> - Sugarcube source code does not define `Math.trunc` anywhere.
> - `Math.trunc` is already built in to JavaScript.

There are many common used methods from Standard JavaScript that are also documented within SugarCube's own documentation, like `<array>.push()` and `<array>.pop()`. :smiley:

Likely to help those new to the whole web-development thing :confused:. Who might not know how to locate the 'official' documentation for such things on MDN, or have yet learnt how to absorb such Software Developer orientated documentation. :neckbeard:

**Comment by BawdyInkSlinger** [comment]
Ah, true. I've updated my title.

**Comment by tmedwards** [comment]
`Math.easeInOut()` is not documented because it's a legacy static method that only exists for Twine 1.4 compatibility.  It's unused by SugarCube.
