### ISSUE TITLE
Upgrade jQuery to the latest version (3.7.1)

### ISSUE THREAD

**Issue by BawdyInkSlinger** [tmedwards/sugarcube-2#269]
**Is your feature request related to a problem?**
This is a list of the changes:
* https://blog.jquery.com/2023/05/11/jquery-3-7-0-released-staying-in-order/
* https://blog.jquery.com/2023/08/28/jquery-3-7-1-released-reliable-table-row-dimensions/

**Describe the solution you'd like.**
Download https://code.jquery.com/jquery-3.7.1.min.js and overwrite the existing jquery.min.js contents

**Additional context.**
The line `const $dataInitPassages = $elems.find('[data-init-passage]');` (found in engine.js) throws an error on jquery 3.6.4 **if** you run the code in Node with JSDOM. It runs as expected in 3.7.1.

I doubt anyone else would find this relevant, but other bug fixes and performance improvements are likely in the upgrade.

**Comment by tmedwards** [comment]
The `devel` branch is currently using jQuery v3.7.0.  I can update that further, but may try that first.

**Comment by BawdyInkSlinger** [comment]
Oops. Done.

**Comment by tmedwards** [comment]
Resolved by 9a817e983f0e52d8306d78d204dc5be9de2cde5d

**Comment by tmedwards** [comment]
Forgot about your PR.  Mea culpa.

**Comment by BawdyInkSlinger** [comment]
NP, thanks!
