### ISSUE TITLE
Quick Accessibility option with the `<<type>>` macro speed?

### ISSUE THREAD

**Issue by manonamora** [tmedwards/sugarcube-2#278]
**Is your feature request related to a problem?**
When using `<<type>>` with a variable (`<<type $var>>`), the speed `0s` displays the letters very quickly, with the animation, forcing to double the passages/text block (one with the `<<type>>` macro and one without) when wanting to add an accessible option to remove animation.

**Describe the solution you'd like.**
When the speed is at 0, could the text be displayed as if the skipKey is pressed? Just the text without the letter by letter animation?
I've tried [messing around with the code](https://github.com/manonamora/SugarCube-Macros/blob/main/typed.js), and only managed to include a setting, that when toggled on, displays the text without animation.

**Describe alternatives you've considered.**
Adding a [toggle setting](https://github.com/manonamora/SugarCube-Macros/blob/main/typed.js), which I realise is not very helpful to include that if the project doesn't even use the macro.

**Comment by tmedwards** [comment]
🤦🏻

**Comment by manonamora** [comment]
sorry and thank you! <3
