### ISSUE TITLE
```&nbsp;``` seems to be discarded by 2.37.0 alpha 17

### ISSUE THREAD

**Issue by selden** [tmedwards/sugarcube-2#280]
**Describe the bug.**
A "bare" ```&nbsp;``` on a line by itself at the beginning of a paragraph seems to be ignored (or discarded) by 2.37.0 alpha 17.

**To Reproduce:**
insert a ```&nbsp;``` as the first line of a paragraph when paragraph indentation is enabled.
 
**Expected behavior.**
The visible text of that paragraph should not be indented.

**Screenshots.**
![no_indent_2 36](https://github.com/tmedwards/sugarcube-2/assets/353932/bbd638b9-884d-4975-99f7-97b31ca132d9)
![indent_2 37](https://github.com/tmedwards/sugarcube-2/assets/353932/d55b0a31-c3fb-49c5-88ae-d8962618ab4e)

**Project details.**
 - SugarCube Version: 2.37.0 alpha 17 (compared to 2.36.1)
 - Included Add-ons: none
 - Included Libraries: none
 - Compiler & Version:  Tweego 2.1.1

**Desktop details.**
 - OS & Version: Windows 10 Pro x64 22H2 (with current patches)
 - Browser & Version  Firefox 119 (64-bit)]

**Smartphone/tablet details.**
n/a

**Additional context.**Background:

My IFs enable automatic paragraph indentation:

in "Story Javascript" they specify

```
Config.cleanupWikifierOutput = true;
```

and in "Story Stylesheet" they declare

```
.passage p {
	   margin-left: 1.0em;
	   margin-right: 1.0em;
	   text-indent: 2.0em;
	   }
```

When using 2.36.1, I can "disable" indentation on a case-by-case basis by specifying a non-breakable space ```&nbsp;``` as the first line of text of a paragraph. The invisible space gets indented but the visible part of the paragraph is not.

This no longer works in 2.37.0 alpha 17. Instead, the visible text of the paragraph is indented.

If this feature cannot be easily restored, is there some other invisible character which can be used for the some purpose?
(A global search-and-replace would be too difficult for me.)

The attached zip includes test_nbsp.tw and the corresponding html and images (as above) demonstrating the problem.

[test_nbsp.zip](https://github.com/tmedwards/sugarcube-2/files/13258105/test_nbsp.zip)

**Comment by tmedwards** [comment]
Frankly.  What you were doing was abusing `v2.36.1`'s substandard `Config.cleanupWikifierOutput` feature.  It was very, very hacky.  While adjustments and fixes can be made if something is truly off with the new code, in general the new behavior is staying.  Thus, your whitespace trick is not coming back.

That said.  You can accomplish the same effect by switching to a non-hacky HTML tag-based solution.  It should work in both `v2.36.1` and `v2.37.0`.

**HTML tag:**
```
<hr no-indent>
```
**Styles:**
```
.passage p {
	margin-left: 1.0em;
	margin-right: 1.0em;
	text-indent: 2.0em;
}

hr[no-indent] {
	display: none;
}
hr[no-indent] + p {
	text-indent: 0;
}
```
**Example:**
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nec enim interdum, commodo eros sit amet, interdum ex. Aliquam faucibus neque non libero dapibus aliquam. Nulla facilisi.

<hr no-indent>
Sed at rhoncus diam, sit amet commodo libero. Duis facilisis, dui varius fringilla consequat, purus urna tincidunt nulla, nec maximus elit nisi ut diam. Nulla aliquam ac erat et interdum.

Phasellus eu euismod velit. Proin placerat gravida lacus, ac tempus tortor volutpat quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. 
```

**Comment by selden** [comment]
Thanks. That does seem a bit more reliable!

Selden
________________________________
