### ISSUE TITLE
Link markup does not recognize HTML Symbol entities

### ISSUE THREAD

**Issue by selden** [tmedwards/sugarcube-2#283]
**Describe the bug.**
Link markup does not recognize HTML Symbol entities

**To Reproduce:**
Use an HTML Symbol entity in the text component of the link markup.

**Expected behavior.**
The symbol should be seen when the markup is rendered.
Instead, the characters comprising the symbol's name are shown.

Symbols *are* shown when the Link macro is used. Markup should show them too.

**Screenshots.**
for chrome w/sugarcube 2.36 and firefox w/sugarcube 2.37 are attached

**Project details.**
 - SugarCube Version: both 2.36.1 and 2.37.0 alpha 18
 - Included Add-ons: none
 - Included Libraries: none
 - Compiler & Version: Tweego 2.1.1

**Desktop details.**
 - OS & Version:  Windows 10 Pro x64 22H2
 - Browser & Version both Chrome 119 (64-bit) and Firefox 119 (64-bit)]

**Smartphone/tablet details.**
 not tested

**Additional context.**
Zip containing test_symbol.tw is attached.

[test_symbol.zip](https://github.com/tmedwards/sugarcube-2/files/13343621/test_symbol.zip)
![firefox_symbol](https://github.com/tmedwards/sugarcube-2/assets/353932/f4f5b68d-27bf-47f1-ad14-61a3b2305d88)
![chrome_symbol](https://github.com/tmedwards/sugarcube-2/assets/353932/c5b88bc0-ef44-4abd-8fc1-71d8a6ad3730)

**Comment by tmedwards** [comment]
From the [link markup documentation](https://www.motoslave.net/sugarcube/2/docs/#markup-link):

> SugarCube's link markup consists of a required Link component and optional Text and Setter components. The Link and Text components may be ***either plain text or any valid TwineScript expression***, […]

The link markup's text component has *never* been treated as HTML, thus HTML named entities and numeric references will not work.

Changing that in v2 would be a breaking change for very little benefit.

If you need such characters in links, either:

* Use the `<<link>` macro.
* Use the HTML `<a>` tag.
* Use the literal character—e.g., `[[Literal characters­©™|…]]

**Comment by selden** [comment]
The underlying issue for me is that I sometimes want multi-word text components not to be broken across multiple lines on the screen. I had hoped to be able to use &nbsp; between them.

Fortunately, it seems that  using the HTML token pair<nobr>...</nobr> around the link markup does what I need.

________________________________________
