### ISSUE TITLE
Twine stacks multiple versions of file when you import to web version, export, then import to desktop version.

### ISSUE THREAD

**Issue by SmallTownBo** [tmedwards/sugarcube-2#289]
**Describe the bug.**
I uploaded a file onto the web version. Then, when I exported and imported that to the desktop version, every single passage had multiple versions of itself. My 190 passage file became 500 passage. Almost all are stacked on top of each other. I think what it's doing is saving over old versions, because I had recently moved and resized some passages, and the copies of those passages where in the old spot, in the old size.

**To Reproduce:**
Import a file to the web version, export it, saving over the file, and then importing that into the desktop version.

**Expected behavior.**
Not duplicate all of my passages on top of each other, making me have to go and manually delete over 300 passages.

**Screenshots.**
![Untitled-1](https://github.com/tmedwards/sugarcube-2/assets/108910246/3c0c200f-ab19-4b83-ac26-e67d44449599)

**Project details.**
 - SugarCube Version: 2.36.1
 - Compiler & Version: Twine 2.8.1.0

**Desktop details.**
 - OS & Version: Windows 10
 - Browser & Version: Brave v1.61.116

**Comment by hituro** [comment]
I tried the same thing, and did not get any passage duplication.

Could you give the steps in more detail? Do you export by publishing to file? As twee? Do you save the file from desktop twine to an external location? Do you overwrite the exported file with the file from the web version before importing? A step by step might help reproduce this.

**Comment by SmallTownBo** [comment]
I worked on it in the desktop version, exported that to HTML file by publishing. I just save it into my harddrive, although not the one that has Windows on it.

Imported it to the web version, made some changes, then exported by publishing it, and saved it over the file I imported. It was an HTML file the entire way through

**Comment by tmedwards** [comment]
This is a tooling issue—see [Twine 2 issue tracker](https://github.com/klembot/twinejs/issues)—not a story format issue.
