### ISSUE TITLE
<<do>> tags not processing comments properly.

### ISSUE THREAD

**Issue by leahiel** [tmedwards/sugarcube-2#300]
**Version**
**Publicly Available Alpha**: SugarCube v2.37.0-alpha.19+10193
**Most Recent Build Available**: SugarCube v2.37.0-alpha.20+1
I did not test the backported `<<do>>` `<<redo>>` macro set for ≤ v2.36.1

**Describe the bug.**
Text within `<<do>>` macros may not be parsing comments properly. For instance, having `<<do>>` within a comment will trigger an error if used within a `<<do>>` macro.

**To Reproduce:**
```
:: APassageName
/* <<do>> */
<<do>>
    No errors from comment outside of do macro!
<</do>>

<br><br>

<<do>>
    Oh look, errors!
    /* <<do>> */
<</do>>
```
![image](https://github.com/tmedwards/sugarcube-2/assets/71794961/80c780a7-3286-428d-a096-3a5cb9b9d77b)

**Expected behavior.**
No error.

**Project details.**
 - SugarCube Version: SugarCube v2.37.0-alpha.19+10193 *and* SugarCube v2.37.0-alpha.20+1
 - Included Add-ons: None
 - Included Libraries: None
 - Compiler & Version: Latest, Tweego, version 2.1.1+81d1d71 (2020-02-25T07:09:26Z) [windows/amd64]

**Desktop details.**
 - OS & Version: Windows 11
 - Browser & Version: Latest version of Firefox, Chrome and Edge

**Comment by tmedwards** [comment]
That is an undocumented "feature" of the `v2` macro parser that isn't limited to the `<<do>>` macro and is not going to be fixed in the `v2.x.x` series.
