### ISSUE TITLE
Verbatim String as macro argument

### ISSUE THREAD

**Issue by boyland** [tmedwards/sugarcube-2#304]
**Describe the bug.**
I would like to use verbatim text as a macro argument, e.g.
```
<<link """<<S>> := <<NP>> <<VP>>""">>
```
Or
```
<<link `"""<<S>> := <<NP>> <<VP>>"""`>>
```
Neither appears to work.

**To Reproduce:**
1. Use one of those form in a Twee File
2. Generate HTML using tweego
3. Load file in browser
4. Error shows up.
  a. No text is generated, possibly the first `""` is taken as an empty string?
  b. `Error: cannot execute macro <<link>>: unable to parse macro argument expression """"<<S>> := <<NP>> <<VP>>"""": missing ) in parenthetical`

**Expected behavior.**
A link with the text `<<S>> := <<NP>> <<VP>>`.

**Screenshots.**
(Hopefully the problem is clear without screenshots.)

**Project details.**
 - SugarCube Version: 2.30.0
 - Included Libraries: *none*
 - Compiler & Version: Tweego 2.1.1+81d1d71

**Desktop details.**
 - OS & Version: Linux Ubuntu 22.04.01
 - Browser & Version: Firefox 125.03 (64-bit)]

**Additional context.**
I may be wrong; perhaps this is expected behavior.  Then I should ask this in the help forum.

**Comment by greyelf** [comment]
@boyland 

SugarCube's [Verbatim Text](https://www.motoslave.net/sugarcube/2/docs/#markup-verbatim-text) markup feature can be used to disable the processing of all markup contained within its delimiteres.
eg. to output `<<S>> := <<NP>> <<VP>>` as plain text in a Passage you would do the following....
```
<nowiki><<S>> := <<NP>> <<VP>></nowiki>
```
...and to output the same as a link's label, you just use single or double quotes to convert the above into a String...
```
<<link "<nowiki><<S>> := <<NP>> <<VP>></nowiki>">><</link>>
```

**Comment by boyland** [comment]
I have confirmed that `<nowiki>` works where `"""` doesn't.  Thanks.
