### ISSUE TITLE
ReqTypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.

### ISSUE THREAD

**Issue by sizhongbin** [tmedwards/sugarcube-2#306]
**Describe the bug.**
When I try to use supabase-js library to fetch data from my database in Supabase, I will get this error. I've tried the same code in a simple HTML file and it works well. 

**To Reproduce:**
1. Put the following code in a file:
 `<script type="module">`
 `  import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js/+esm').then(({`
 `    createClient`
 `  }) => {`
 `    const supabase = createClient('https://gsxwebojwtxgmtvohfdv.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzeHdlYm9qd3R4Z210dm9oZmR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTc2NDg2MzAsImV4cCI6MjAzMzIyNDYzMH0.1XhzomAchqFjRrjscXtXIV4KUmnStjxkOF0cV7NLRQY');`
`    console.log('Supabase Instance: ', supabase);`
`    supabase.auth.signInWithPassword({`
`      email: 'test@test',`
`      password: 'test1234'`
`    }).then(({ data, error }) => {`
`      console.log('SUCCEED. Response: ', data);`
`      supabase.from('character').select('character_id').then(`
`        ({ data, error }) => {`
`          console.log('Data: ', data);`
`          console.log('Error: ', error);`
`      })`
`    })`
`  })`
`</script>`
2. Add the code in the compiled HTML's head using tweego with --head.
3. See the error in console.

**Expected behavior.**
The code should works like how it is in simple HTML file. data should be an array and error should be null.

**Screenshots.**
N/A

**Project details.**
 - SugarCube Version: 2.36.1
 - Included Add-ons: nope
 - Included Libraries: supabase.js
 - Compiler & Version: Tweego 2.1.1

**Smartphone/tablet details.**
 - Device: Xiaomi 12X
 - OS & Version: Android 13
 - Browser & Version: Kiwi browser. 

**Additional context.**

**Comment by tmedwards** [comment]
Why are you using such an old version of SugarCube and what is the error?

Also, you need to format that code.  Use a code fence.

**Comment by sizhongbin** [comment]
> Why are you using such an old version of SugarCube and what is the error?
> 
> Also, you need to format that code. Use a code fence.

Sorry I'm using 2.36.1. I've updated.

**Comment by sizhongbin** [comment]
Actually I'm not sure if its a bug or not. And I'm not sure if its caused by sugarcube or by tweego.
I've also tried to use the supabase REST API instead of supabase-js library and everything goes well.
``const url = `${SBP.url}/rest/v1/character`;``
`const headers = new Headers({`
`   apikey: setup.anonKey,`
``    Authorization: `Bearer ${setup.access_token}` ``
`});`
`fetch(url, {`
`  method: 'GET',`
`  headers: headers`
`})`
`  .then(response => {`
`    if (!response.ok) {`
`      throw new Error('Network response was not ok');`
`    }`
`    console.log(response);`
`    return response.json();`
`  })`
`  .then(data => {`
`    console.log('data: ', data);`
`  })`
`  .catch(error => {`
`    console.error('error:', error);`
`  });`
`};`
And some other functions like auth.signUp(), auth.signInWithPassword(), insert() in supabase-js also works well in tweego compiled HTML. Looks like the error only occurs when I try to use select(). That's quite strange.

**Comment by sizhongbin** [comment]
Looks like this error will not occur in v2.37.0. I will do some more test on the new version.
Thanks.
