### ISSUE TITLE
ariaDisabled anchors don't have the not-allowed cursor

### ISSUE THREAD

**Issue by cjneidhart** [tmedwards/sugarcube-2#310]
**Describe the bug.**
Creating a `<a id="myAnchor">` element and then disabling it with `$('#myAnchor')` in 2.36 would qualify that element to have the `cursor: not-allowed` CSS rule applied. But in a [recent commit](https://github.com/tmedwards/sugarcube-2/commit/77266a0915ffe5129ecd040cff561c80588d2332), this rule was removed. This might be intentional, but it seems like an oversight. The history buttons on the side still have the correct cursor, since they are matched by the `:disabled` pseudo-class. But `<a>` elements are not matched by `:disabled`.

**To Reproduce:**
1. Create an anchor element, e.g. `<a id="myAnchor">Example Anchor</a>`
2. Disable it with `$('#myAnchor').ariaDisabled(true)`
3. Move the cursor over the anchor
4. The cursor changes to a pointer, implying the element is interactive

**Expected behavior.**
The cursor changes to imply the link is not interactive

**Project details.**
 - SugarCube Version: 2.37.0
 -  Tweego 2.1.1

**Desktop details.**
 - OS & Version: Linux
 - Browser & Version: Firefox 128.0, Chromium 126.0.6478.182

**Comment by tmedwards** [comment]
Fixed.  Will be in the patch release.
