### ISSUE TITLE
variables set to undefined/Infinity do not revive properly

### ISSUE THREAD

**Issue by Brokenstorm** [tmedwards/sugarcube-2#323]
**Describe the bug.**
when the page is refreshed (F5), all variables set to undefined/Infinity are not revived properly.
undefined variables are set to `[ "(revive:)", "undefined" ]`
Infinity variables are set to `null`

**To Reproduce:**
1. set any variable to undefined/Infinity 
2. move to another passage (to create a moment)
3. refresh the page

**Expected behavior.**
The variables are set to undefined/Infinity 

**Project details.**
 - SugarCube Version: 2.37.2
 - Compiler & Version: Tweego 2.1.1

**Comment by greyelf** [comment]
Why are you assigning a value like [undefined](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined), whose purpose is to indicate that a variable / property / method / function / etc hasn't been defined yet (eg. doesn't exist), to a variable in the first place?

That value is designed to be used in comparisons to determine is something has been defined, not assignments.

If you indicate that something shouldn't exist, then it makes sense that it's existence isn't persisted or revived. After all why revived something that hasn't been defined.

**Comment by Brokenstorm** [comment]
> Why are you assigning a value like undefined

Some macros set object value to undefined.
2.36.1 revived those object property correctly

**Comment by tmedwards** [comment]
@greyelf This is indeed a bug.

Fixed in [84c396d](https://github.com/tmedwards/sugarcube-2/commit/84c396d372a5731239189de09419fa759efec5a2).
