### ISSUE TITLE
Image markup puts alt text into wrong attribute

### ISSUE THREAD

**Issue by eladnarra** [tmedwards/sugarcube-2#328]
**Describe the bug.**
The docs state that the optional title value in the image markup will "be used as the alt text of the image." However, if you put `[img[Title|Image]]`, the HTML output is: `<img src="Image" title="Title">`

This output is incorrect; alternative text should go in the `alt` attribute for accessibility.

**To Reproduce:**
1. Insert an image in a passage using the image markup.
2. Publish the file.
3. Use developer tools (or open resulting HTML file) to check the `<img>` created.

**Expected behavior.**
The HTML output should be: `<img src="Image" alt="Title">`

**Project details.**
 - SugarCube Version: 2.37.3
 - Included Add-ons: none
 - Included Libraries: none
 - Compiler & Version: Twine 2.9.2.0

**Desktop details.**
 - OS & Version: Windows 10

**Additional context.**
Some assistive tech can access/announce text in the `title`, but some simply can't. Others will announce both if they are present - which means that the same text **should not** be duplicated in an alt attribute as a fix. 

More info: [img: The title attribute (mdn web docs)](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#the_title_attribute)

**Comment by tmedwards** [comment]
When that code was written (ca. the 2000s or even the 1990s) the `title` tag *was* the way to specify alternate text on an image.  So, not a bug per se.

That said, things have moved on, as they are want to do, and today you are correct.  The `alt` tag is a better fit.
