### ISSUE TITLE
It'd be nice if the `findNewest()` method was exposed to users and documented.

### ISSUE THREAD

**Issue by ChapelR** [tmedwards/sugarcube-2#329]
**Is your feature request related to a problem?**
It would be nice to get the latest save without loading it, for example, to compare it's timestamp to the last passage render to let users know their changes haven't been saved. Not super pressing as the functionality can be recreated, and somewhat niche, but since the work is already done, I don't see the harm in exposing this method as part of the API.

**Describe the solution you'd like.**
`Save.browser.newest()` => returns the most recent save (slot or auto), but without loading it, just return the save object

**Describe alternatives you've considered.**

**Additional context.**

**Comment by tmedwards** [comment]
Done.

**Comment by tmedwards** [comment]
**NOTE:** None of the APIs actually return the save object, instead returning a *save descriptor* object (detailed in the docs).

If the goal here is to get at the save data (`save.state`), what the descriptor lacks, then they're going to be disappointed.

If the goal here is to is to know if the save is newer than some datestamp, then the descriptor does have a `date` property (detailed in the docs) that they can use.
