### ISSUE TITLE
[WORKAROUND] br are still included in widgets that are children of the <<do>> macro when Config.passages.nobr = true

### ISSUE THREAD

**Issue by wjkmartin** [tmedwards/sugarcube-2#331]
**Describe the bug.**
\<br> are still included in widgets that are children of the \<\<do>> macro when Config.passages.nobr = true

**To Reproduce:**
1. Config.passages.nobr = true
2. Create a \<\<do>\> macro with a direct child of a widget that has new lines

e.g. 

```
:: StoryInit
<<run Config.passages.nobr = true >>

:: Start
<<do>>
<<WidgetName>>
<</do>>

:: WidgetPassage [widget]
<<widget "WidgetName">>
intentional spaces below


<</widget>>
```

**Expected behavior.**
No \<br> to appear in the document

**Screenshots.**
(Not from the given example)

![image](https://github.com/user-attachments/assets/9f36d823-69de-429f-9204-23c7606547d8)

**Project details.**
 - SugarCube Version: 2.37.0
 - Compiler & Version: Tweego latest

**Desktop details.**
 - OS & Version: Windows 10
 - Browser & Version: Any

**Additional context.**
Workaround exists: add the "nobr" tag to the widget passage and it works as expected

**Comment by manonamora** [comment]
```
Config.passages.nobr = true;
```
Should be placed in your JavaScript not in your StoryInit passage.

(I get not bug when in JavaScript, only when the code is in StoryInit, Config APIs should not be there)

**Comment by wjkmartin** [comment]
> ```
> Config.passages.nobr = true;
> ```
> 
> Should be placed in your JavaScript not in your StoryInit passage.
> 
> (I get not bug when in JavaScript, only when the code is in StoryInit, Config APIs should not be there)

Confirmed that was the issue!
