### ISSUE TITLE
Line continuation with nobr only sometimes works

### ISSUE THREAD

**Issue by Xetanai** [tmedwards/sugarcube-2#36]
I'm using SugarCube 2.31.1 and Tweego 2.1.1

I've set nobr globally using `Config.passages.nobr = true;` and have a widget that I'm trying to use to display the current ingame time.

The widget is below:
```
<<widget "currenttime">>
    <<if $gameDate.getUTCHours() eq 0>>
        12\
    <<elseif $gameDate.getUTCHours() gt 12>>
        <<print $gameDate.getUTCHours() - 12>>\
    <<else>>
        <<print $gameDate.getUTCHours()>>\
    <</if>>:\
    <<if $gameDate.getUTCMinutes() lt 10>>0<</if>><<print $gameDate.getUTCMinutes()>>\
    <<if $gameDate.getUTCHours() gte 12>>PM<<else>>AM<</if>>\
<</widget>>
```

Given $gameDate is a JS Date object for 8 AM (The date is irrelevant), the output is `8:\ 00\ AM`, meaning that the line continuation marker after the print macro for the hour was parsed properly, and the one after AM, but all others are ignored and output

Other times have no effect and the same line continuation characters are ignored,

**Comment by tmedwards** [comment]
Any markup that depends on line positioning, line continuations included, is not compatible with the no-break features, which turn sources into a single line.

**Comment by Xetanai** [comment]
I see. Aside from just building a string inside the widget and printing the result all at once, is there any other way to accomplish this that I'm missing?

**Comment by tmedwards** [comment]
Not really.  Using no-break reduces your options a bit.  There are several ways to go about what you're trying to do—e.g., [templates](http://www.motoslave.net/sugarcube/2/docs/#markup-template) or [macros](http://www.motoslave.net/sugarcube/2/docs/#macro-api)—but all of them would end up building a string and then either returning it or rendering it, so they wouldn't be especially different from a widget that did it.

**Comment by Xetanai** [comment]
Alright, thanks for your help. I'll look into those
