### ISSUE TITLE
Ability to add note to save slot

### ISSUE THREAD

**Issue by rambdev** [tmedwards/sugarcube-2#39]
I would love to see a way to add a custom name or small note to the slot upon save, similar to Sierra's "Quest" games.

![twine-sc2_customsavebox](https://user-images.githubusercontent.com/64991612/81491726-77f03200-925f-11ea-9893-1ec87956ad83.png)

**Comment by Jaydax1729** [comment]
Oddly sometimes I see details in the second section but mostly I see only load or Delete

**Comment by HiEv** [comment]
Are you talking about the _user_ being able to do that or the _developer_?

Either way, you can do that by creating a [`Config.saves.onSave`](http://www.motoslave.net/sugarcube/2/docs/#config-api-property-saves-onsave) function and set the "title" property on the "save" object, which will set the title of the save.  For a simple example, you could put this in your JavaScript section:
```
Config.saves.onSave = function (save) {
	save.title = prompt("Enter Save Slot Title:");
};
```
and that would prompt the user to give the save slot a custom title.

Hope that helps!  :smiley:

**Comment by rambdev** [comment]
@HiEv Sorry, should have clarified that. I'd want it to be an end-user function, thought being able to set that as a developer is nice too.

Much appreciated for the function idea. I'll definitely utilize that in my current project. 😃

While it's possible to create a function to do this in individual projects, I personally think it would do well as a default feature, or at least something toggleable like a dedicated config api option.

**Comment by HiEv** [comment]
@rambdev - Perhaps you didn't notice my edit, but the code there now will let the end-user set the title of the save slot.

Try it out.  :smiley:

**Comment by rambdev** [comment]
@HiEv Ah, I didn't see that. The original code was allowing end-user usage as well as far as I can tell, but I'll give that a try too. Thanks!

**Comment by tmedwards** [comment]
Closed in favor of the v3 issue: https://github.com/tmedwards/sugarcube-3-prealpha/issues/1

**NOTE:** The v3 repository is not yet public, so the above link probably will not work for you until it is.
