### ISSUE TITLE
RFE: option to <<textbox>> for actions rather than a passage

### ISSUE THREAD

**Issue by boyland** [tmedwards/sugarcube-2#44]
I've found it limiting to have the only way to handle a CR on a textbox is to go to a new passage.  I created my own version `<<textboxlink>>` that silently expands its payload when CR is pressed.  I could do a pull-request, if you'd like.  Otherwise, the only real difference is changing
```
// If Return/Enter is pressed, set the variable and, optionally, forward to another passage.
if (ev.which === 13) { // 13 is Return/Enter
	ev.preventDefault();
	State.setVar(varName, this.value);

	if (passage != null) { // lazy equality for null
		Engine.play(passage);
	}
}
```
to
```
// If Return/Enter is pressed, set the variable and, perform link
if (ev.which === 13) { // 13 is Return/Enter
	ev.preventDefault();
	State.setVar(varName, this.value); // redundant?
	Wikifier.wikifyEval(contents);
}
```
where `contents` is set to `this.payload[0].contents.trim()` in the outer scope.

**Comment by tmedwards** [comment]
I think you're forgetting that `<<textbox>>` is not a container macro—i.e., it has no contents.

**Comment by boyland** [comment]
Well, that's why my macro is called `<<textboxlink>>` and it *is* a container macro.  A clunky name, but gets across the idea, I hope.

**Comment by tmedwards** [comment]
Ah, my mistake.  I thought you wanted to modify `<<textbox>>` itself.

There's already an add-on macro, `<<textboxplus>>`, that's a containerized version of `<<textbox>>`, which also doesn't drop the ability to forward as yours does.

* **Gist:** [`<<textboxplus>>`](https://gist.github.com/tmedwards/4c9061ab13ab01626e27c83d157a7311)

I prefer modifications to core macros as add-ons, so I think we'll leave it as that.

**Comment by boyland** [comment]
Thanks.  The add-on looks like exactly what I need.  Is it obvious how to use an add-on?  Or is it used the same way that I defined my custom-macro: copy JavaScript code into my story?

**Comment by tmedwards** [comment]
You copy the given JavaScript into the JavaScript section of your project.  Add-ons generally come with documentation, instructions and usage, but `<<textboxplus>>` was a quick Gist for a request.
