### ISSUE TITLE
[Docs] Clarify that "current passage" means the current moment, not the passage the code is running from within. 

### ISSUE THREAD

**Issue by ChapelR** [tmedwards/sugarcube-2#51]
For example, the `tags()` function features this line: 

> If omitted, will default to the current passage.

Some users have interpreted this to mean the **passage the code is in** rather than the **passage associated with the current moment**, e.g., they believe a `tags()` call in `PassageHeader` would return the tags of the `PassageHeader` passage. 

I do not think the docs as written are necessarily unclear, but I think it wouldn't hurt to specify what is meant by the "current passage."

**Comment by tmedwards** [comment]
Seems good?

**Comment by tmedwards** [comment]
Made two commits addressing this.  Better?

**Comment by ChapelR** [comment]
Looks good to me.
