### ISSUE TITLE
Castellano (Spanish from Spain) Translation

### ISSUE THREAD

**Issue by Gexgekko** [tmedwards/sugarcube-2#53]
The current spanish translation you can find on https://www.motoslave.net/sugarcube/2/ is not from Spain, it's from somewhere in south america I think. I have no problem with that but some things look like they were translated wrongly as they don't make sense in spanish. I decided to translate them on my own and now they are readable by Españoles and any other spanish speaking people, not only by the specific community that made the original translation.

I have the file here but I don't know how to upload it as I've never worked with github as a team or as a contributor (never really used git other than branching for different versions).

**Comment by tmedwards** [comment]
First.  Let me say, thank you!

As far as the origin of the current Español localization.  I don't recall them offering regional information with it, so I'm unsure.  If it's offered, I do try to include it—as you can see with the two Português locations.

As to the file.  You should be able to attach it to a reply here.

**Comment by Gexgekko** [comment]
[es-locale.zip](https://github.com/tmedwards/sugarcube-2/files/4819383/es-locale.zip)

Here it is. I hope it works!

**Comment by tmedwards** [comment]
Merged.
