### ISSUE TITLE
Setting menu disappears on reload

### ISSUE THREAD

**Issue by Purzelkater** [tmedwards/sugarcube-2#54]
The following code I have added to my start passage:

```javascript
<<script>>
	var settingFontSize = function () {
		var emSize = (settings.fontSize/100).toString();
		document.getElementById("passages").style.fontSize = emSize+"em";
	};
	Setting.addHeader("");
	Setting.addRange("fontSize", {
		label    : "Font size",
		min      : 100,
		max      : 200,
		step     : 5,
		default  : 100,
		onInit   : settingFontSize,
		onChange : settingFontSize
	});	
	Setting.addToggle("playSound", {
		label    : "Play music?",
		default  : false
	});
	Setting.save();
<</script>>
```

Starting a new game the setting dialog works like expected. But after reloading the game (reload the window on browser or close and open the html file) or after resetting the values (with the default reset button on setting dialog) the setting button disappears from the menu.

**Comment by ChapelR** [comment]
That is expected behavior. If your start passage doesn't run, neither does that code. It should be in story JavaScript. If you absolutely insist on having it in a passage, use `StoryInit`.

**Comment by Purzelkater** [comment]
That's it! Thank you. I hadn't thought of that the Setting setup would be temporary on the Start passage.
