### ISSUE TITLE
Error when building from source

### ISSUE THREAD

**Issue by z3n17** [tmedwards/sugarcube-2#80]
Just a heads up. The version of sugarcube I found distributed with tweego was 2.30. I noticed there was a newer version so I wanted to try building this from source. When I ran `node build.js` it failed because `writeFileContents` was expecting a string instead of a number, I was able to get it to build by casting the version number to a string. So I got it working in the end but I decided to report the small hiccup just so you're aware. Have a nice day!

**Comment by tmedwards** [comment]
Continues to work for me as-is.  What version of NodeJS were you using?

**Comment by z3n17** [comment]
Probably `v15.0.1`, that's what I have now and I don't think it has updated in the last two days.

**Comment by tmedwards** [comment]
Hmm.  Looks to be caused by a change to the `fs.writeFileSync()` API in Node.js v14.
