### ISSUE TITLE
The <<type>> macro's typing speed also applies to the starting character, effectively extending the start delay.

### ISSUE THREAD

**Issue by cyrusfirheir** [tmedwards/sugarcube-2#92]
Test cases:
```html
<<type 1ms start 1s>>
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc nec lorem id felis posuere tempus at nec lacus.
<</type>>
```
```html
<<type 1s start 1ms>>
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc nec lorem id felis posuere tempus at nec lacus.
<</type>>
```
Both take the same amount of time to start.

**Comment by tmedwards** [comment]
(Preface.  Writing this from my phone.)

The first character(s) typed in your examples are non-printable.  Meaning that the first printable character will indeed show both the initial start delay and the printing speed delay of whatever non-printable characters it's already typed.

Did you try your test when the first character is a printable?

**Comment by cyrusfirheir** [comment]
I'd thought of that when it was first noticed, that it could be something invisible being printed, but It happens even when used like this:
```html
<<type 1s start 1ms>>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc nec lorem id felis posuere tempus at nec lacus.<</type>>
```
